import React from "react";
import Head from "next/head";
import config from "config.json";
import { useAutoAnimate } from "@formkit/auto-animate/react";

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  const title = config.config[0]?.options[0]?.value;
  const description = config.config[1]?.options[0]?.value;
  const [parent] = useAutoAnimate();
  return (
    <>
      <Head>
        <title>{title ? title : "4everland"}</title>
        <meta
          name="description"
          content={description ? description : "Generated by 4everland"}
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex min-h-screen flex-col items-center bg-[var(--novel-white)] font-mono sm:px-5 sm:pt-[calc(15vh)]">
        <ul
          ref={parent}
          className="scrollbar-thumb-rounded scrollbar-thin scrollbar-track-gray-100 scrollbar-thumb-gray-200 relative flex h-[550px] w-full max-w-screen-lg flex-wrap content-start gap-6 overflow-y-auto border-stone-200 bg-white p-12 px-8 sm:mb-[calc(1vh)] sm:rounded-lg sm:border sm:px-12 sm:shadow-lg"
        >
          {children}
        </ul>
      </section>
    </>
  );
}
